### ISSUE TITLE
Files Missing

### ISSUE THREAD

**Issue by nkhedekar** [AgileDrones/Blackbird-Dataset#1]
The files mentioned in the instructions of the readme are missing in the repository.

**Comment by Winter-Guerra** [comment]
Hi Nikhil,

We're still working on refining the dataset download tool in order to make the process scalable. Since the dataset is large (~4.72TB), this process is proving to be nontrivial. We hope to have it publically available by Monday.

Best,
-Winter

**Comment by nkhedekar** [comment]
Hi Winter, 

Thank you for the clarification. I look forward to it. 

Best,
Nikhil

**Comment by edowson** [comment]
The ROS bag files are missing. Additionally there is no IMU data (*.csv) files.

Please consider creating a separate torrent file containing only the ROS bag and IMU data, for people who have already started downloading the 4.72TB dataset, else it will interrupt the current downloads for the images and videos.

**Comment by Winter-Guerra** [comment]
Hi all,

I've updated the dataset with ROS Bags. These bags have IMU and TF data. The torrent file still works for the image files, but there is now a direct download option (check the README).

As for IMU CSVs, the ROS bags can be converted to CSVs using https://github.com/AtsushiSakai/rosbag_to_csv/

Please let me know what you think!
Best,
-Winter
