### ISSUE TITLE
Download utility broken

### ISSUE THREAD

**Issue by bayerj** [AgileDrones/Blackbird-Dataset#3]
The download seems to be broken, there is a syntax error in line 27: https://github.com/AgileDrones/Blackbird-Dataset/blob/master/downloadUtilities/downloaderUtility.py#L27

**Comment by bayerj** [comment]
Thanks the info!

**Comment by Winter-Guerra** [comment]
Hello Justin,

The README of the repo has been updated with a direct download link. Please let me know if you find this method easier for downloading the dataset!

Best,
-Winter
