### ISSUE TITLE
Need .msg for blackbird/MotorRPM 

### ISSUE THREAD

**Issue by barzanisar** [AgileDrones/Blackbird-Dataset#4]
Hi, 

Can you please upload the .msg file for blackbird/MotorRPM so that this dataset is usable by others?
because when I echo the topic, it gives me the following error:

`$ rostopic echo /blackbird/rotor_rpm`
`ERROR: Cannot load message class for [blackbird/MotorRPM]. Are your messages built?`

**Comment by Winter-Guerra** [comment]
Hi barzanisar,

Thanks for your feedback! I'm terribly sorry for the inconvenience, I'll upload the RPM and PWM `.msg` files as soon as I can. Those files were mistakenly left out of the git repo during our raw LCM->ROS data conversion process, so I'll have to dig around a bit for them. 

Best,
-Winter

**Comment by Winter-Guerra** [comment]
Hi barzanisar,

I've uploaded the missing `.msg` files and added instructions on how to build the message types in `README.md` under "Using the Dataset in ROS". Please don't hesitate to ask if you have further issues!

Best,
-Winter
